name: 'crypto_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'crypto_analytics'

# These configurations specify where dbt should look for different types of files.
model-paths: ['models']
analysis-paths: ['analyses']
test-paths: ['tests']
seed-paths: ['seeds']   # make sure your CSVs are inside dbt/seeds/
macro-paths: ['macros']
snapshot-paths: ['snapshots']

target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_packages'

# Configuring models
models:
  crypto_analytics:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
    intermediate:
      +materialized: ephemeral
      +schema: intermediate

tests:
  +store_failures: true

seeds:
  crypto_analytics:
    crypto_prices_raw:
      +column_types:
        id: bigint
        symbol: text
        name: text
        current_price: numeric
        market_cap: numeric
        total_volume: numeric
        price_change_24h: numeric
        price_change_percentage_24h: numeric
        market_cap_rank: integer
        extracted_at: timestamp
        created_at: timestamp
    pipeline_runs:
      +column_types:
        id: bigint
        run_id: text
        stage: text
        status: text
        records_processed: bigint
        error_message: text
        started_at: timestamp
        completed_at: timestamp

