apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: crypto_warehouse
    user: postgres
    secureJsonData:
      password: 'crypto_password_123'
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1500
      timescaledb: false
    isDefault: true