"""Initial migration

Revision ID: 202508081555_initial_migration
Revises:
Create Date: 2025-08-08 15:55:00.000000

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "202508081555_initial_migration"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crypto_prices_raw",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("current_price", sa.Float(), nullable=False),
        sa.Column("market_cap", sa.Float(), nullable=True),
        sa.Column("total_volume", sa.Float(), nullable=True),
        sa.Column("price_change_24h", sa.Float(), nullable=True),
        sa.Column("price_change_percentage_24h", sa.Float(), nullable=True),
        sa.Column("market_cap_rank", sa.Integer(), nullable=True),
        sa.Column("extracted_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("price_change_percentage_1h", sa.Float(), nullable=True),
        sa.Column("price_change_percentage_7d", sa.Float(), nullable=True),
        sa.Column("circulating_supply", sa.Float(), nullable=True),
        sa.Column("total_supply", sa.Float(), nullable=True),
        sa.Column("max_supply", sa.Float(), nullable=True),
        sa.Column("ath", sa.Float(), nullable=True),
        sa.Column("atl", sa.Float(), nullable=True),
        sa.Column("last_updated", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_crypto_prices_raw_extracted_at",
        "crypto_prices_raw",
        ["extracted_at"],
        unique=False,
    )
    op.create_index(
        "ix_crypto_prices_raw_symbol", "crypto_prices_raw", ["symbol"], unique=False
    )
    op.create_index(
        "ix_crypto_prices_symbol_extracted_at",
        "crypto_prices_raw",
        ["symbol", "extracted_at"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_symbol_extracted_at", "crypto_prices_raw", ["symbol", "extracted_at"]
    )

    op.create_table(
        "pipeline_runs",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("run_id", sa.String(length=100), nullable=False),
        sa.Column("stage", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("records_processed", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_pipeline_runs_run_id_stage",
        "pipeline_runs",
        ["run_id", "stage"],
        unique=False,
    )
    op.create_unique_constraint("uq_run_id_stage", "pipeline_runs", ["run_id", "stage"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_run_id_stage", "pipeline_runs", type_="unique")
    op.drop_index("ix_pipeline_runs_run_id_stage", table_name="pipeline_runs")
    op.drop_table("pipeline_runs")
    op.drop_constraint("uq_symbol_extracted_at", "crypto_prices_raw", type_="unique")
    op.drop_index(
        "ix_crypto_prices_symbol_extracted_at", table_name="crypto_prices_raw"
    )
    op.drop_index("ix_crypto_prices_raw_symbol", table_name="crypto_prices_raw")
    op.drop_index("ix_crypto_prices_raw_extracted_at", table_name="crypto_prices_raw")
    op.drop_table("crypto_prices_raw")
    # ### end Alembic commands ###
